## These are the Packages you might need to install in your PC to run this repository.
if (!requireNamespace("BiocManager", quietly = TRUE))
  install.packages("BiocManager")
install.packages("gghighlight")
install.packages("knitr")
install.packages("dplyr")
install.packages("rstatix")
install.packages("openxlsx")
install.packages("gam")
install.packages("foreach")
install.packages("RcppArmadillo")
install.packages("RColorBrewer")
install.packages("Rcpp")
install.packages("gplots")
install.packages("gridExtra")
install.packages("data.table")
install.packages("stats")
install.packages("dplyr")
install.packages("plyr")
install.packages("future")
install.packages("readxl")
install.packages("calibrate")
install.packages("ggrepel")
install.packages("colorRamp2")
install.packages("circlize")
install.packages("doParallel")
install.packages("BiocParallel")
install.packages("stringr")
install.packages("gplot")

install.packages("RCurl")
install.packages("tidyr")
install.packages("ggpubr")
remotes::install_version(package = 'Seurat', version = package_version('4.3.0'))

install.packages("htmltools")
BiocManager::install("BiocStyle",force=T)

BiocManager::install("HDO.db",force=T)
BiocManager::install( "org.Mm.eg.db",force=T)
BiocManager::install("org.Dr.eg.db",force=T)
BiocManager::install("ComplexHeatmap",force=T)
BiocManager::install("edgeR",force=T)
BiocManager::install("clusterProfiler",force=T)
BiocManager::install("ggplot2",force=T)

BiocManager::install("DESeq2")
BiocManager::install("EnrichedHeatmap")
BiocManager::install("DESeq2")

########################################
#sessionInfo()
